//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_ProyectoWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCar
    {
        public int ConsecutiveCar { get; set; }
        public long ConsecutiveUser { get; set; }
        public int ConsecutiveProduct { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
    
        public virtual tbProduct tbProduct { get; set; }
        public virtual tbUser tbUser { get; set; }
    }
}
