//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_ProyectoWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProduct
    {
        public int ConsecutiveProduct { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int ConsecutiveCategory { get; set; }
        public bool State { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual tbCategory tbCategory { get; set; }
    }
}
