//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_ProyectoWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        public long ConsecutiveUser { get; set; }
        public string Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool State { get; set; }
        public int ConsecutivePerfil { get; set; }
    
        public virtual tbPerfil tbPerfil { get; set; }
    }
}
